### ISSUE TITLE
Property getters and setters of base classes not working in derived class

### ISSUE THREAD

**Issue by zacharygriffee** [kbravh/multi-class#5]
Property getters and setters of base classes not working from derived class; probably an easy fix I think. I use property getters/setters a lot for database purposes. I have tried other multiple inheritance modules and this one is nearly perfect for my project. Here is an image of the flaw. 

![image](https://user-images.githubusercontent.com/5599507/98785824-35a0dc80-23cb-11eb-8083-fb5d67feb6b3.png)

**Comment by kbravh** [comment]
@zacharygriffee Thanks for catching that! I'll take a look at this today and see what I can find.

**Comment by kbravh** [comment]
@zacharygriffee This should be resolved by the recent pull request #6. You can see the change if you update to version 1.0.7.

**Comment by zacharygriffee** [comment]
Fix works great! Thank you.
